---
sudo: false
language: rust
rust:
  - stable

install:
  - brew install sdl2

os:
  - osx

branches:
  only:
    - master

env:
  - ARCH=x86_64
  - ARCH=i686

script:
  - cargo build

addons:
  apt:
    packages:
      - gcc-multilib
