---
sudo: true
language: rust
rust:
  - stable

os:
  - linux
  - osx

env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib

branches:
  only:
    - master

env:
  - ARCH=x86_64
  - ARCH=i686

script:
  - cargo build
  - cargo test

addons:
  apt:
    packages:
      - gcc-multilib
