---
sudo: false
language: rust
rust:
  - stable
  - nightly

os:
  - linux
  - osx

branches:
  only:
    - master

env:
  - ARCH=x86_64
  - ARCH=i686

script:
  - cargo build

addons:
  apt:
    packages:
      - gcc-multilib
