---
sudo: true
language: rust
rust:
  - stable

os:
  - linux
  - osx

env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib

install:
  - sudo apt-get update
  - sudo apt-get install libsdl1.2-dev libsdl-mixer1.2-dev libsdl-image1.2-dev

branches:
  only:
    - master

env:
  - ARCH=x86_64
  - ARCH=i686

script:
  - cargo build

addons:
  apt:
    packages:
      - gcc-multilib
