[package]
name = "gomoku"
version = "0.1.0"
authors = [
  "Guillaume Bersac",
  "adjivas <adjivas@users.noreply.github.com>"
]
description = "Game of GO from 42 school"
repository = "https://github.com/gbersac/gomoku_42.git"
